{% set name = "swifttools" %}
{% set version = "3.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/swifttools-{{ version }}.tar.gz
  sha256: 7fb62adf20896e75622a9a966a5ee6ded356c2ae83d8a4a312ee40cd498e1962

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - requests
    - python-jose
    - pandas
    - tabulate
    - numpy

test:
  imports:
    - swifttools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/DrPhilEvans/swifttools
  summary: Tools for users of the Swift satellite
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaeakle
